  name: 'Project Regexes'
  description: 'Creates a github output based on file changes for other jobs to conditionally check'
  inputs:
    regexes:
      description: 'Regexes to match project to file paths'
      required: true
  outputs:
    is_changed:
      description: 'boolean value describing if regexes match files changed in PR'

  runs:
    using: "composite"
    steps:
      - uses: actions/checkout@v4
      - name: Match regex and create env variable
        shell: bash
        run: |
          REGEXES=('${{ inputs.regexes }}')

          echo $REGEXES
                   
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            base_sha=${{ github.event.pull_request.base.sha }}
          else
            base_sha='main'
          fi
          
          git fetch origin $base_sha
          files=$(git diff --name-only $base_sha ${{ github.sha }})
          
          echo "Changed files:"
          echo -e "$files\n"

          for file in $files; do
            for regex in "${REGEXES[@]}"; do
              if [[ $file =~ $regex ]]; then
                is_changed='true'
                echo "is_changed=true" >> $GITHUB_ENV
                exit 0
              fi
            done
          done

          echo "is_changed=false" >> $GITHUB_ENV
          exit 0

