name: ci-ai

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git reference'
        required: true
        default: 'main'

jobs:
  run-ai:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.ref }}

    - name: Run AI related tasks
      run: |
        echo "Running AI tasks..."
        python ai/main.py
