name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch all branches and PR refs
      run: |
        git fetch origin +refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/pull/*

    - name: Determine Changed Files
      id: filter
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          base_ref="origin/${{ github.base_ref }}"
          head_ref="origin/${{ github.head_ref }}"
        else
          base_ref="HEAD^"
          head_ref="HEAD"
        fi
    
        # AI directories
        AI_DIRS=("ai/")
        AI_CHANGED="false"
        for dir in "${AI_DIRS[@]}"; do
          git diff --quiet $base_ref $head_ref -- $dir
          if [ $? -eq 1 ]; then
            AI_CHANGED="true"
            break
          fi
        done
    
        # UI directories
        UI_DIRS=("ui/")
        UI_CHANGED="false"
        for dir in "${UI_DIRS[@]}"; do
          git diff --quiet $base_ref $head_ref -- $dir
          if [ $? -eq 1 ]; then
            UI_CHANGED="true"
            break
          fi
        done
    
        # SIM directories
        SIM_DIRS=("sim/")
        SIM_CHANGED="false"
        for dir in "${SIM_DIRS[@]}"; do
          git diff --quiet $base_ref $head_ref -- $dir
          if [ $? -eq 1 ]; then
            SIM_CHANGED="true"
            break
          fi
        done
    
        # Outputting to GitHub environment
        echo "AI_CHANGED=$AI_CHANGED" >> $GITHUB_ENV
        echo "UI_CHANGED=$UI_CHANGED" >> $GITHUB_ENV
        echo "SIM_CHANGED=$SIM_CHANGED" >> $GITHUB_ENV

    - name: Trigger AI Workflow
      if: env.AI_CHANGED == 'true'
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.MY_PAT }}" \
        "https://api.github.com/repos/${{ github.repository }}/actions/workflows/ai.yaml/dispatches" \
        -d "{\"ref\":\"${{ github.ref }}\"}"

    - name: Trigger UI Workflow
      if: env.UI_CHANGED == 'true'
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.MY_PAT }}" \
        "https://api.github.com/repos/${{ github.repository }}/actions/workflows/ui.yaml/dispatches" \
        -d "{\"ref\":\"${{ github.ref }}\"}"

    - name: Trigger SIM Workflow
      if: env.SIM_CHANGED == 'true'
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.MY_PAT }}" \
        "https://api.github.com/repos/${{ github.repository }}/actions/workflows/sim.yaml/dispatches" \
        -d "{\"ref\":\"${{ github.ref }}\"}"
