name: Conditional Directory Check

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-ai:
    runs-on: [ubuntu-latest]
    steps:
      - name: Check Directory Changes
        uses: ./.github/actions/check-directory-changes

  run-ai:
    needs: check-ai
    if: needs.check-ai.outputs.changed == 'true' || github.event_name == 'schedule'
    runs-on: [ubuntu-latest]
    steps:
        - run: |
            echo "Running AI"

  run-ui:
    runs-on: [ubuntu-latest]
    steps:
      - run: |
          echo "Running UI"

  run-sim:
    runs-on: [ubuntu-latest]
    steps:
      - run: |
          echo "Running Sim"
