name: Conditional Directory Check

on:
  pull_request:
    branches:
      - main

jobs:
  check_changes:
    runs-on: ubuntu-latest

    outputs:
      ai-changed: ${{ env.AI_CHANGED }}
      ui-changed: ${{ env.UI_CHANGED }}
      sim-changed: ${{ env.SIM_CHANGED }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check directory changes using Python script
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BASE_BRANCH=${{ github.event.pull_request.base.sha }}
          else
            # git fetch origin main:main
            BASE_BRANCH=main
          fi

          python check_directory_changes.py "$BASE_BRANCH" ${{ github.sha }} > changes.txt
          cat changes.txt
          if grep -q "AI_CHANGED=true" changes.txt; then echo "AI_CHANGED=true" >> $GITHUB_ENV; fi
          if grep -q "UI_CHANGED=true" changes.txt; then echo "UI_CHANGED=true" >> $GITHUB_ENV; fi
          if grep -q "SIM_CHANGED=true" changes.txt; then echo "SIM_CHANGED=true" >> $GITHUB_ENV; fi

  run-ai:
    needs: check_changes
    runs-on: ubuntu-latest
    if: needs.check_changes.outputs.ai-changed == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Execute steps for AI
        run: echo "AI related patterns matched."

      - name: Run AI program
        run: |
          python ai/main.py

  run-ui:
    needs: check_changes
    runs-on: ubuntu-latest
    if: needs.check_changes.outputs.ui-changed == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Execute steps for UI
        run: echo "UI related patterns matched."

      - name: Run UI Program
        run: |
          python ui/main.py

  run-sim:
    needs: check_changes
    runs-on: ubuntu-latest
    if: needs.check_changes.outputs.sim-changed == 'true'
    steps:
      - name: Execute steps for sim
        run: echo "SIM related patterns matched."
