name: Main Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      # Prevent infinite loops
      - '.github/workflows/ai.yml'
      - '.github/workflows/sim.yml'
      - '.github/workflows/ui.yml'
  pull_request:
    branches:
      - main

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:

    # Fetch all history so that we can do a proper diff
    
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch all branches and PR refs
      run: |
        git fetch origin +refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/pull/*

    - name: Check changed files over the entire PR
      id: getfiles
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # For pull requests, compare against the base ref of the PR
            files=$(git diff --name-only origin/${{ github.base_ref }}...origin/${{ github.head_ref }})
        else
            # For regular pushes, compare against the previous commit
            files=$(git diff --name-only HEAD^ HEAD)
        fi
        echo "::set-output name=changed::$files"
        
    - name: Trigger other workflows
      run: |
        changed_files="${{ steps.getfiles.outputs.changed }}"
        echo "Changed files: $changed_files"

        # Depending on the changed file, trigger the respective workflow
        if [[ $changed_files == *"ai/"* ]]; then
          echo "AI files changed. Triggering AI workflow."
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/ai.yml/dispatches" \
          -d "{\"ref\":\"${{ github.ref }}\"}"
        fi

        if [[ $changed_files == *"sim/"* ]]; then
          echo "SIM files changed. Triggering SIM workflow."
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/sim.yml/dispatches" \
          -d "{\"ref\":\"${{ github.ref }}\"}"
        fi

        if [[ $changed_files == *"ui/"* ]]; then
          echo "UI files changed. Triggering UI workflow."
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/ui.yml/dispatches" \
          -d "{\"ref\":\"${{ github.ref }}\"}"
        fi
