name: Main Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      # Prevent infinite loops
      - '.github/workflows/ai.yaml'
      - '.github/workflows/sim.yaml'
      - '.github/workflows/ui.yaml'
  pull_request:
    branches:
      - main

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
    # Fetch all history so that we can do a proper diff
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch all branches and PR refs
      run: |
        git fetch origin +refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/pull/*

    - name: Check changed files over the entire PR
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "Comparing for PR"
          # For pull requests, compare against the base ref of the PR
          files=$(git diff --name-only origin/${{ github.base_ref }}...origin/${{ github.head_ref }} | tr '\n' ' ')
        else
          echo "Comparing for Push"
          # For regular pushes, compare against the previous commit
          files=$(git diff --name-only HEAD^ HEAD | tr '\n' ' ')
        fi
        echo "CHANGED_FILES=$files" >> $GITHUB_ENV

    - name: Trigger other workflows
      run: |
        AI_DIRS=("ai/")
        UI_DIRS=("ui/")
        SIM_DIRS=("sim/")

        trigger_workflow() {
          dir_array=("$@")
          for dir in "${dir_array[@]}"; do
            if [[ $CHANGED_FILES == *"$dir"* ]]; then
              echo "Files in $dir changed. Triggering ${dir%/*} workflow."
              curl -X POST -H "Authorization: token ${{ secrets.MY_PAT }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/${dir%/*}.yaml/dispatches" \
              -d "{\"ref\":\"${{ github.ref }}\"}"
              break
            fi
          done
        }

        trigger_workflow "${AI_DIRS[@]}"
        trigger_workflow "${UI_DIRS[@]}"
        trigger_workflow "${SIM_DIRS[@]}"
