name: Conditional Directory Check

on:
  pull_request:
    branches:
      - main

jobs:
  check_changes:
    runs-on: ubuntu-latest

    outputs:
      ai-changed: ${{ env.AI_CHANGED }}
      ui-changed: ${{ env.UI_CHANGED }}
      sim-changed: ${{ env.SIM_CHANGED }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check directory changes and match regex
        id: check_changes_step
        run: |
          # Define regex patterns for each type (Modify these patterns as per your needs)
          AI_REGEXES=("^ai/.*" \
                      "^shared/.*")
          UI_REGEXES=("^ui/.*" \
                      "^shared/.*")
          SIM_REGEXES=("^sim/.*"\
                       "^shared/.*")

          AI_CHANGED="false"
          UI_CHANGED="false"
          SIM_CHANGED="false"

          files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})

          # Print changed files
          echo "Changed files:"
          echo "$files"
          echo "-------------------------"

          for file in $files; do
            # Check against AI regex patterns
            for regex in "${AI_REGEXES[@]}"; do
              if [[ $file =~ $regex ]]; then
                echo "Matched: $file with regex $regex"
                AI_CHANGED="true"
                break
              fi
            done
          
            # Check against UI regex patterns
            for regex in "${UI_REGEXES[@]}"; do
              if [[ $file =~ $regex ]]; then
                echo "Matched: $file with regex $regex"
                UI_CHANGED="true"
                break
              fi
            done
          
            # Check against SIM regex patterns
            for regex in "${SIM_REGEXES[@]}"; do
              if [[ $file =~ $regex ]]; then
                echo "Matched: $file with regex $regex"
                SIM_CHANGED="true"
                break
              fi
            done
          done
          echo "AI_CHANGED=$AI_CHANGED" >> $GITHUB_ENV
          echo "UI_CHANGED=$UI_CHANGED" >> $GITHUB_ENV
          echo "SIM_CHANGED=$SIM_CHANGED" >> $GITHUB_ENV

  run-ai:
    needs: check_changes
    runs-on: ubuntu-latest
    if: needs.check_changes.outputs.ai-changed == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Execute steps for ai
        run: echo "AI related patterns matched."

      - name: Execute steps for ai
        run: |
          python ai/main.py

  run-ui:
    needs: check_changes
    runs-on: ubuntu-latest
    if: needs.check_changes.outputs.ui-changed == 'true'
    steps:
      - name: Execute steps for ui
        run: echo "UI related patterns matched."

  run-sim:
    needs: check_changes
    runs-on: ubuntu-latest
    if: needs.check_changes.outputs.sim-changed == 'true'
    steps:
      - name: Execute steps for sim
        run: echo "SIM related patterns matched."
