name: CI

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changes:
    runs-on: [ubuntu-latest]
    outputs:
      ai: ${{ steps.check-ai.outputs.is_changed }}
      ui: ${{ steps.check-ui.outputs.is_changed }}
      sim: ${{ steps.check-sim.outputs.is_changed }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check-directory-changes
        id: check-ai
        with:
          regexes: "^ai/.* ^shared/.* ^.github/.*"
      - uses: ./.github/actions/check-directory-changes
        id: check-ui
        with:
          regexes: "^ui/.* ^shared/.* ^.github/.*"
      - uses: ./.github/actions/check-directory-changes
        id: check-sim
        with:
          regexes: "^sim/.* ^shared/.* ^.github/.*"

  run-ai:
    needs: check-changes
    if: needs.check-changes.outputs.ai == 'true' || github.event_name == 'schedule'
    runs-on: [ubuntu-latest]
    steps:
        - run: |
            echo "Running AI"

  run-ui:
    needs: check-changes
    if: needs.check-changes.outputs.ui == 'true' || github.event_name == 'schedule'
    runs-on: [ubuntu-latest]
    steps:
      - run: |
          echo "Running UI"

  run-sim:
    needs: check-changes
    if: needs.check-changes.outputs.sim == 'true' || github.event_name == 'schedule'
    runs-on: [ubuntu-latest]
    steps:
      - run: |
          echo "Running Sim"
