name: Main Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      # Prevent infinite loops
      - '.github/workflows/ai.yaml'
      - '.github/workflows/sim.yaml'
      - '.github/workflows/ui.yaml'
  pull_request:
    branches:
      - main

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:

    # Fetch all history so that we can do a proper diff
    
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch all branches and PR refs
      run: |
        git fetch origin +refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/pull/*

    - name: Check changed files over the entire PR
      id: getfiles
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "Comparing for PR"
          # For pull requests, compare against the base ref of the PR
          files=$(git diff --name-only origin/${{ github.base_ref }}...origin/${{ github.head_ref }} | tr '\n' ',')
        else
          echo "Comparing for Push"
          # For regular pushes, compare against the previous commit
          files=$(git diff --name-only HEAD^ HEAD | tr '\n' ',')
        fi
        echo "CHANGED=$files" >> $GITHUB_ENV
        
    - name: Trigger other workflows
      run: |
        changed_files="$CHANGED"
        echo "Changed files: $changed_files"

        ref_name="${{ github.ref }}"
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          ref_name="${{ github.head_ref }}"
        fi

        # Depending on the changed file, trigger the respective workflow
        
        if [[ $changed_files == *"ai/"* ]]; then
          echo "AI files changed. Triggering AI workflow."
          curl -X POST -H "Authorization: token ${{ secrets.MY_PAT }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/ai.yml/dispatches" \
          -d "{\"ref\":\"$ref_name\"}"
        fi

        if [[ $changed_files == *"ui/"* ]]; then
          echo "UI files changed. Triggering UI workflow."
          curl -X POST -H "Authorization: token ${{ secrets.MY_PAT }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/ui.yml/dispatches" \
          -d "{\"ref\":\"$ref_name\"}"
        fi

        if [[ $changed_files == *"sim/"* ]]; then
          echo "SIM files changed. Triggering SIM workflow."
          curl -X POST -H "Authorization: token ${{ secrets.MY_PAT }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/sim.yml/dispatches" \
          -d "{\"ref\":\"$ref_name\"}"
        fi
