name: ci-ai

on:
  pull_request:
    branches:
      - main

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Echo
      run: |
        echo "Executing steps for changes in ui"
