name: ci-ui

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git reference'
        required: true
        default: 'main'

jobs:
  run-ui:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.ref }}

    - name: Run UI related tasks
      run: |
        echo "Running UI tasks..."
